=== riccardodannibale/SITO-PALESTRA/APPLICAZIONE/site/dtd/abbonamenti.dtd
<!ELEMENT abbonamenti (abbonamento+)>
<!ELEMENT abbonamento (tipo, durata_mesi, prezzo)>
<!ATTLIST abbonamento id ID #REQUIRED>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT durata_mesi (#PCDATA)>
<!ELEMENT prezzo (#PCDATA)>

=== riccardodannibale/SITO-PALESTRA/APPLICAZIONE/site/xml/abbonamenti.xml
<?xml version="1.0"?>
<!DOCTYPE abbonamenti SYSTEM "../dtd/abbonamenti.dtd">
<abbonamenti>
  <abbonamento id="1">
    <tipo>Mensile</tipo>
    <durata_mesi>1</durata_mesi>
    <prezzo>30.00</prezzo>
  </abbonamento>
  <abbonamento id="2">
    <tipo>Trimestrale</tipo>
    <durata_mesi>3</durata_mesi>
    <prezzo>80.00</prezzo>
  </abbonamento>
  <abbonamento id="3">
    <tipo>Annuale</tipo>
    <durata_mesi>12</durata_mesi>
    <prezzo>300.00</prezzo>
  </abbonamento>
</abbonamenti>
