=== riccardodannibale/SITO-PALESTRA/APPLICAZIONE/site/dtd/feedback.dtd
<!ELEMENT feedback (valutazione_corso+)>
<!ELEMENT valutazione_corso (id_lezione, voto, id_user_abbonamento)>
<!ELEMENT id_lezione (#PCDATA)>
<!ELEMENT voto (#PCDATA)>
<!ELEMENT id_user_abbonamento (#PCDATA)>

=== riccardodannibale/SITO-PALESTRA/APPLICAZIONE/site/xml/feedback.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE feedback SYSTEM "../dtd/feedback.dtd">
<feedback>
  <valutazione_corso>
    <id_lezione>1</id_lezione>
    <voto>1</voto>
    <id_user_abbonamento>a1</id_user_abbonamento>
    <data_valutazione>2025-08-06 10:15:00</data_valutazione>
  </valutazione_corso>
  <valutazione_corso>
    <id_lezione>1</id_lezione>
    <voto>2</voto>
    <id_user_abbonamento>a2</id_user_abbonamento>
    <data_valutazione>2025-08-16 14:03:44</data_valutazione>
  </valutazione_corso>
  <valutazione_corso>
    <id_lezione>3</id_lezione>
    <voto>1</voto>
    <id_user_abbonamento>a1</id_user_abbonamento>
    <data_valutazione>2025-08-12 09:20:00</data_valutazione>
  </valutazione_corso>
  <valutazione_corso>
    <id_lezione>6</id_lezione>
    <voto>4</voto>
    <id_user_abbonamento>a5</id_user_abbonamento>
    <data_valutazione>2024-12-02 08:50:00</data_valutazione>
  </valutazione_corso>
  <valutazione_corso>
    <id_lezione>2</id_lezione>
    <voto>3</voto>
    <id_user_abbonamento>a2</id_user_abbonamento>
    <data_valutazione>2025-08-17 14:47:27</data_valutazione>
  </valutazione_corso>
  <valutazione_corso id="1">
    <id_lezione>3</id_lezione>
    <id_user_abbonamento>a2</id_user_abbonamento>
    <voto>1</voto>
    <data_valutazione>2025-08-12 13:21:04</data_valutazione>
  </valutazione_corso>
  <valutazione_corso id="2">
    <id_lezione>5</id_lezione>
    <id_user_abbonamento>a2</id_user_abbonamento>
    <voto>2</voto>
    <data_valutazione>2025-09-13 16:37:20</data_valutazione>
  </valutazione_corso>
  <valutazione_corso>
    <id_lezione>1</id_lezione>
    <voto>5</voto>
    <id_user_abbonamento>a3</id_user_abbonamento>
    <data_valutazione>2025-08-06 11:00:00</data_valutazione>
  </valutazione_corso>
  <valutazione_corso>
    <id_lezione>2</id_lezione>
    <voto>4</voto>
    <id_user_abbonamento>a4</id_user_abbonamento>
    <data_valutazione>2025-08-17 19:00:00</data_valutazione>
  </valutazione_corso>
  <valutazione_corso>
    <id_lezione>3</id_lezione>
    <voto>4</voto>
    <id_user_abbonamento>a3</id_user_abbonamento>
    <data_valutazione>2025-08-13 09:45:00</data_valutazione>
  </valutazione_corso>
  <valutazione_corso>
    <id_lezione>5</id_lezione>
    <voto>5</voto>
    <id_user_abbonamento>a3</id_user_abbonamento>
    <data_valutazione>2025-08-21 08:10:00</data_valutazione>
  </valutazione_corso>
  <valutazione_corso>
    <id_lezione>6</id_lezione>
    <voto>3</voto>
    <id_user_abbonamento>a6</id_user_abbonamento>
    <data_valutazione>2024-12-03 09:00:00</data_valutazione>
  </valutazione_corso>
  <valutazione_corso>
    <id_lezione>8</id_lezione>
    <voto>4</voto>
    <id_user_abbonamento>a2</id_user_abbonamento>
    <data_valutazione>2025-09-02 20:05:00</data_valutazione>
  </valutazione_corso>
  <valutazione_corso>
    <id_lezione>8</id_lezione>
    <voto>5</voto>
    <id_user_abbonamento>a10</id_user_abbonamento>
    <data_valutazione>2025-09-02 20:20:00</data_valutazione>
  </valutazione_corso>
  <valutazione_corso>
    <id_lezione>9</id_lezione>
    <voto>4</voto>
    <id_user_abbonamento>a1</id_user_abbonamento>
    <data_valutazione>2025-02-13 09:00:00</data_valutazione>
  </valutazione_corso>
  <valutazione_corso>
    <id_lezione>9</id_lezione>
    <voto>3</voto>
    <id_user_abbonamento>a6</id_user_abbonamento>
    <data_valutazione>2025-02-13 09:15:00</data_valutazione>
  </valutazione_corso>
  <valutazione_corso>
    <id_lezione>5</id_lezione>
    <voto>3</voto>
    <id_user_abbonamento>a4</id_user_abbonamento>
    <data_valutazione>2025-08-22 07:30:00</data_valutazione>
  </valutazione_corso>
  <valutazione_corso>
    <id_lezione>1</id_lezione>
    <voto>1</voto>
    <id_user_abbonamento>a7</id_user_abbonamento>
    <data_valutazione>2025-08-10 12:00:00</data_valutazione>
  </valutazione_corso>
  <valutazione_corso>
    <id_lezione>2</id_lezione>
    <voto>5</voto>
    <id_user_abbonamento>a12</id_user_abbonamento>
    <data_valutazione>2025-08-18 09:00:00</data_valutazione>
  </valutazione_corso>
  <valutazione_corso>
    <id_lezione>5</id_lezione>
    <voto>4</voto>
    <id_user_abbonamento>a13</id_user_abbonamento>
    <data_valutazione>2025-08-21 20:00:00</data_valutazione>
  </valutazione_corso>
  <valutazione_corso>
    <id_lezione>6</id_lezione>
    <voto>5</voto>
    <id_user_abbonamento>a5</id_user_abbonamento>
    <data_valutazione>2024-12-05 08:30:00</data_valutazione>
  </valutazione_corso>
</feedback>
