=== riccardodannibale/SITO-PALESTRA/APPLICAZIONE/site/dtd/reputazione.dtd
<!ELEMENT reputazioni (utente*)>
<!ELEMENT utente (username, punteggio, ultima_attivita)>
<!ATTLIST utente id CDATA #REQUIRED>
<!ELEMENT username (#PCDATA)>
<!ELEMENT punteggio (#PCDATA)>
<!ELEMENT ultima_attivita (#PCDATA)>

=== riccardodannibale/SITO-PALESTRA/XML DI PROVA/xml/reputazione.xml
<?xml version="1.0"?>
<!DOCTYPE reputazioni SYSTEM "./dtd/reputazione.dtd">
<reputazioni>
  <utente id="1">
    <username>mario</username>
    <punteggio>85.0</punteggio>
    <ultima_attivita>2025-07-07</ultima_attivita>
  </utente>
  <utente id="2">
    <username>luisa</username>
    <punteggio>96.5</punteggio>
    <ultima_attivita>2025-09-13</ultima_attivita>
  </utente>
  <utente id="3">
    <username>gianni</username>
    <punteggio>10.0</punteggio>
    <ultima_attivita>2025-08-01</ultima_attivita>
  </utente>
  <utente id="4">
    <username>sara</username>
    <punteggio>20.0</punteggio>
    <ultima_attivita>2025-08-15</ultima_attivita>
  </utente>
  <utente id="5">
    <username>alice</username>
    <punteggio>45.0</punteggio>
    <ultima_attivita>2025-09-13</ultima_attivita>
  </utente>
  <utente id="6">
    <username>bob</username>
    <punteggio>38.0</punteggio>
    <ultima_attivita>2025-09-13</ultima_attivita>
  </utente>
  <utente id="7">
    <username>carla</username>
    <punteggio>15.0</punteggio>
    <ultima_attivita>2025-08-01</ultima_attivita>
  </utente>
  <utente id="8">
    <username>dario</username>
    <punteggio>22.0</punteggio>
    <ultima_attivita>2025-09-13</ultima_attivita>
  </utente>
  <utente id="9">
    <username>admin</username>
    <punteggio>0.0</punteggio>
    <ultima_attivita>2025-07-04</ultima_attivita>
  </utente>
  <utente id="10">
    <username>root</username>
    <punteggio>10.0</punteggio>
    <ultima_attivita>2025-09-13</ultima_attivita>
  </utente>
</reputazioni>

=== riccardodannibale/SITO-PALESTRA/APPLICAZIONE/site/xml/reputazione.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE reputazioni PUBLIC "SYSTEM" "../dtd/reputazione.dtd">
<reputazioni>
  <utente id="9">
    <username>admin</username>
    <punteggio base="0.00" last_calc="2026-09-14T17:56:09+02:00" last_value="0.00">0.00</punteggio>
    <ultima_attivita>2026-09-14</ultima_attivita>
  </utente>
  <utente id="5">
    <username>alice</username>
    <punteggio base="0.00" last_calc="2026-09-14T17:56:09+02:00" last_value="2.50">2.50</punteggio>
    <ultima_attivita>2026-09-14</ultima_attivita>
  </utente>
  <utente id="6">
    <username>bob</username>
    <punteggio base="0.00" last_calc="2026-09-14T17:56:09+02:00" last_value="1.50">1.50</punteggio>
    <ultima_attivita>2026-09-14</ultima_attivita>
  </utente>
  <utente id="7">
    <username>carla</username>
    <punteggio base="0.00" last_calc="2026-09-14T17:56:09+02:00" last_value="0.00">0.00</punteggio>
    <ultima_attivita>2026-09-14</ultima_attivita>
  </utente>
  <utente id="8">
    <username>dario</username>
    <punteggio base="0.00" last_calc="2026-09-14T17:56:09+02:00" last_value="0.00">0.00</punteggio>
    <ultima_attivita>2026-09-14</ultima_attivita>
  </utente>
  <utente id="3">
    <username>gianni</username>
    <punteggio base="0.00" last_calc="2026-09-14T17:56:09+02:00" last_value="1.00">1.00</punteggio>
    <ultima_attivita>2026-09-14</ultima_attivita>
  </utente>
  <utente id="2">
    <username>luisa</username>
    <punteggio base="0.00" last_calc="2026-09-14T17:56:09+02:00" last_value="2.00">2.00</punteggio>
    <ultima_attivita>2026-09-14</ultima_attivita>
  </utente>
  <utente id="1">
    <username>mario</username>
    <punteggio base="0.00" last_calc="2026-09-14T17:56:09+02:00" last_value="2.00">2.00</punteggio>
    <ultima_attivita>2026-09-14</ultima_attivita>
  </utente>
  <utente id="10">
    <username>root</username>
    <punteggio base="0.00" last_calc="2026-09-14T17:56:09+02:00" last_value="0.00">0.00</punteggio>
    <ultima_attivita>2026-09-14</ultima_attivita>
  </utente>
  <utente id="4">
    <username>sara</username>
    <punteggio base="0.00" last_calc="2026-09-14T17:56:09+02:00" last_value="1.00">1.00</punteggio>
    <ultima_attivita>2026-09-14</ultima_attivita>
  </utente>
</reputazioni>
